"""Core tool metadata catalog."""

from typing import Dict, Any
from assistant.tools.models import logger

CORE_TOOLS = {
    "nmap": {
        "name": "nmap",
        "binary": "nmap",
        "ecosystem": "apt",
        "install_cmd": "apt install nmap",
        "version_flags": ["--version", "-V"],
        "version_required": ">=7.0.0",
        "category": "scanner",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://nmap.org/book/man.html",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "masscan": {
        "name": "masscan",
        "binary": "masscan",
        "ecosystem": "apt",
        "install_cmd": "apt install masscan",
        "version_flags": ["--version"],
        "version_required": ">=1.0.0",
        "category": "scanner",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/robertdavidgraham/masscan",
        "deprecated": False,
        "priority": 8,
        "speed": "fast",
        "accuracy": "medium"
    },
    "nuclei": {
        "name": "nuclei",
        "binary": "nuclei",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest",
        "version_flags": ["-version"],
        "version_required": ">=3.0.0",
        "category": "scanner",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/projectdiscovery/nuclei",
        "deprecated": False,
        "priority": 9,
        "speed": "fast",
        "accuracy": "high"
    },
    "subfinder": {
        "name": "subfinder",
        "binary": "subfinder",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest",
        "version_flags": ["-version"],
        "version_required": ">=2.0.0",
        "category": "recon",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://github.com/projectdiscovery/subfinder",
        "deprecated": False,
        "priority": 10,
        "speed": "fast",
        "accuracy": "high"
    },
    "sqlmap": {
        "name": "sqlmap",
        "binary": "sqlmap",
        "ecosystem": "apt",
        "install_cmd": "apt install sqlmap",
        "version_flags": ["--version"],
        "version_required": ">=1.0.0",
        "category": "pentest",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://sqlmap.org/",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "volatility": {
        "name": "volatility",
        "binary": "vol.py",
        "ecosystem": "pip",
        "install_cmd": "pip install volatility",
        "version_flags": ["--version"],
        "version_required": ">=2.0.0",
        "category": "forensics",
        "risk": "low",
        "alternatives": ["volatility3"],
        "docs_url": "https://github.com/volatilityfoundation/volatility",
        "deprecated": False,
        "priority": 8,
        "speed": "medium",
        "accuracy": "high"
    },
    "rustscan": {
        "name": "rustscan",
        "binary": "rustscan",
        "ecosystem": "cargo",
        "install_cmd": "cargo install rustscan",
        "version_flags": ["--version"],
        "version_required": ">=2.0.0",
        "category": "scanner",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/RustScan/RustScan",
        "deprecated": False,
        "priority": 7,
        "speed": "fast",
        "accuracy": "medium"
    },
    "httpx": {
        "name": "httpx",
        "binary": "httpx",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest",
        "version_flags": ["-version"],
        "version_required": ">=1.0.0",
        "category": "network",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/projectdiscovery/httpx",
        "deprecated": False,
        "priority": 9,
        "speed": "fast",
        "accuracy": "high"
    },
    "ffuf": {
        "name": "ffuf",
        "binary": "ffuf",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/ffuf/ffuf/v2/cmd/ffuf@latest",
        "version_flags": ["-v"],
        "version_required": ">=2.0.0",
        "category": "network",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://github.com/ffuf/ffuf",
        "deprecated": False,
        "priority": 10,
        "speed": "fast",
        "accuracy": "high"
    },
    "gobuster": {
        "name": "gobuster",
        "binary": "gobuster",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/OJ/gobuster/v3/cmd/gobuster@latest",
        "version_flags": ["--version"],
        "version_required": ">=3.0.0",
        "category": "network",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://github.com/OJ/gobuster",
        "deprecated": False,
        "priority": 8,
        "speed": "medium",
        "accuracy": "high"
    },
}

# Add more tools as needed - target 80-100 curated security tools
# This is a representative sample showing the structure

logger.info(f"Loaded {len(CORE_TOOLS)} core tools from metadata")
