"""Core tool metadata catalog."""

from typing import Dict, Any
from assistant.tools.models import logger

CORE_TOOLS = {
    "nmap": {
        "name": "nmap",
        "binary": "nmap",
        "ecosystem": "apt",
        "install_cmd": "apt install nmap",
        "version_flags": ["--version", "-V"],
        "version_required": ">=7.0.0",
        "category": "scanner",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://nmap.org/book/man.html",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "nuclei": {
        "name": "nuclei",
        "binary": "nuclei",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest",
        "version_flags": ["-version"],
        "version_required": ">=3.0.0",
        "category": "scanner",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/projectdiscovery/nuclei",
        "deprecated": False,
        "priority": 9,
        "speed": "fast",
        "accuracy": "high"
    },
    "subfinder": {
        "name": "subfinder",
        "binary": "subfinder",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest",
        "version_flags": ["-version"],
        "version_required": ">=2.0.0",
        "category": "recon",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://github.com/projectdiscovery/subfinder",
        "deprecated": False,
        "priority": 10,
        "speed": "fast",
        "accuracy": "high"
    },
    "subzy": {
        "name": "subzy",
        "binary": "subzy",
        "ecosystem": "go",
        "install_cmd": "go install github.com/LukaSikic/subzy@latest",
        "version_flags": ["--help"],
        "version_required": ">=1.0.0",
        "category": "recon",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/LukaSikic/subzy",
        "deprecated": False,
        "priority": 8,
        "speed": "fast",
        "accuracy": "medium"
    },
    "assetfinder": {
        "name": "assetfinder",
        "binary": "assetfinder",
        "ecosystem": "go",
        "install_cmd": "go install github.com/tomnomnom/assetfinder@latest",
        "version_flags": ["--help"],
        "version_required": ">=0.1.0",
        "category": "recon",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/tomnomnom/assetfinder",
        "deprecated": False,
        "priority": 7,
        "speed": "fast",
        "accuracy": "medium"
    },
    "sqlmap": {
        "name": "sqlmap",
        "binary": "sqlmap",
        "ecosystem": "apt",
        "install_cmd": "apt install sqlmap",
        "version_flags": ["--version"],
        "version_required": ">=1.0.0",
        "category": "pentest",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://sqlmap.org/",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "volatility3": {
        "name": "volatility3",
        "binary": "vol",
        "ecosystem": "pip",
        "install_cmd": "pip install volatility3",
        "version_flags": ["--version"],
        "version_required": ">=1.0.0",
        "category": "forensics",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/volatilityfoundation/volatility3",
        "deprecated": False,
        "priority": 8,
        "speed": "medium",
        "accuracy": "high"
    },
    "rustscan": {
        "name": "rustscan",
        "binary": "rustscan",
        "ecosystem": "cargo",
        "install_cmd": "cargo install rustscan",
        "version_flags": ["--version"],
        "version_required": ">=2.0.0",
        "category": "scanner",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/RustScan/RustScan",
        "deprecated": False,
        "priority": 7,
        "speed": "fast",
        "accuracy": "medium"
    },
    "httpx": {
        "name": "httpx",
        "binary": "httpx",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest",
        "version_flags": ["-version"],
        "version_required": ">=1.0.0",
        "category": "network",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/projectdiscovery/httpx",
        "deprecated": False,
        "priority": 9,
        "speed": "fast",
        "accuracy": "high"
    },
    "ffuf": {
        "name": "ffuf",
        "binary": "ffuf",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/ffuf/ffuf/v2/cmd/ffuf@latest",
        "version_flags": ["-v"],
        "version_required": ">=2.0.0",
        "category": "network",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://github.com/ffuf/ffuf",
        "deprecated": False,
        "priority": 10,
        "speed": "fast",
        "accuracy": "high"
    },
    "gobuster": {
        "name": "gobuster",
        "binary": "gobuster",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/OJ/gobuster/v3/cmd/gobuster@latest",
        "version_flags": ["--version"],
        "version_required": ">=3.0.0",
        "category": "network",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://github.com/OJ/gobuster",
        "deprecated": False,
        "priority": 8,
        "speed": "medium",
        "accuracy": "high"
    },
    "metasploit": {
        "name": "metasploit",
        "binary": "msfconsole",
        "ecosystem": "script",
        "install_cmd": "curl https://raw.githubusercontent.com/rapid7/metasploit-framework/master/msfinstall | sudo bash",
        "version_flags": ["--version"],
        "version_required": ">=6.0.0",
        "category": "pentest",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://www.metasploit.com/",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "zaproxy": {
        "name": "zaproxy",
        "binary": "zaproxy",
        "ecosystem": "apt",
        "install_cmd": "apt install zaproxy",
        "version_flags": ["-version"],
        "version_required": ">=2.0.0",
        "category": "pentest",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://www.zaproxy.org/",
        "deprecated": False,
        "priority": 9,
        "speed": "medium",
        "accuracy": "high"
    },
    "aircrack-ng": {
        "name": "aircrack-ng",
        "binary": "aircrack-ng",
        "ecosystem": "apt",
        "install_cmd": "apt install aircrack-ng",
        "version_flags": ["--version"],
        "version_required": ">=1.0.0",
        "category": "wireless",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://www.aircrack-ng.org/",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "john": {
        "name": "john",
        "binary": "john",
        "ecosystem": "apt",
        "install_cmd": "apt install john",
        "version_flags": ["--list=build-info"],
        "version_required": ">=1.9.0",
        "category": "password",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://www.openwall.com/john/",
        "deprecated": False,
        "priority": 9,
        "speed": "medium",
        "accuracy": "high"
    },
    "autopsy": {
        "name": "autopsy",
        "binary": "autopsy",
        "ecosystem": "apt",
        "install_cmd": "apt install autopsy",
        "version_flags": ["-h"],
        "version_required": ">=4.0.0",
        "category": "forensics",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://www.sleuthkit.org/autopsy/",
        "deprecated": False,
        "priority": 7,
        "speed": "medium",
        "accuracy": "high"
    },
    "dirsearch": {
        "name": "dirsearch",
        "binary": "dirsearch",
        "ecosystem": "pip",
        "install_cmd": "pip install dirsearch",
        "version_flags": ["--help"],
        "version_required": ">=0.4.0",
        "category": "network",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://github.com/maurosoria/dirsearch",
        "deprecated": False,
        "priority": 8,
        "speed": "medium",
        "accuracy": "high"
    },
    "python3": {
        "name": "python3",
        "binary": "python3",
        "ecosystem": "apt",
        "install_cmd": "apt install python3",
        "version_flags": ["--version"],
        "version_required": ">=3.0.0",
        "category": "runtime",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://python.org",
        "deprecated": False,
        "priority": 10,
        "speed": "fast",
        "accuracy": "high"
    },
    "hydra": {
        "name": "hydra",
        "binary": "hydra",
        "ecosystem": "apt",
        "install_cmd": "apt install hydra",
        "version_flags": ["-h"],
        "version_required": ">=9.0",
        "category": "password",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/vanhauser-thc/thc-hydra",
        "deprecated": False,
        "priority": 9,
        "speed": "medium",
        "accuracy": "high"
    },
    "hashcat": {
        "name": "hashcat",
        "binary": "hashcat",
        "ecosystem": "apt",
        "install_cmd": "apt install hashcat",
        "version_flags": ["--version"],
        "version_required": ">=6.0.0",
        "category": "password",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://hashcat.net/hashcat/",
        "deprecated": False,
        "priority": 9,
        "speed": "fast",
        "accuracy": "high"
    },
    "amass": {
        "name": "amass",
        "binary": "amass",
        "ecosystem": "go",
        "install_cmd": "go install -v github.com/owasp-amass/amass/v4/...@latest",
        "version_flags": ["version"],
        "version_required": ">=4.0.0",
        "category": "recon",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://github.com/owasp-amass/amass",
        "deprecated": False,
        "priority": 9,
        "speed": "slow",
        "accuracy": "high"
    },
    "sublist3r": {
        "name": "sublist3r",
        "binary": "sublist3r",
        "ecosystem": "apt",
        "install_cmd": "apt install sublist3r",
        "version_flags": ["-h"],
        "version_required": ">=1.0",
        "category": "recon",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/aboul3la/Sublist3r",
        "deprecated": False,
        "priority": 8,
        "speed": "medium",
        "accuracy": "medium"
    },
    "netcat": {
        "name": "netcat",
        "binary": "nc",
        "ecosystem": "apt",
        "install_cmd": "apt install netcat-openbsd",
        "version_flags": ["-h"],
        "version_required": ">=1.0",
        "category": "network",
        "risk": "low",
        "alternatives": ["ncat", "nc.traditional"],
        "docs_url": "https://nc110.sourceforge.io/",
        "deprecated": False,
        "priority": 10,
        "speed": "fast",
        "accuracy": "high"
    },
    "masscan": {
        "name": "masscan",
        "binary": "masscan",
        "ecosystem": "apt",
        "install_cmd": "apt install masscan",
        "version_flags": ["--version"],
        "version_required": ">=1.3",
        "category": "scanner",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://github.com/robertdavidgraham/masscan",
        "deprecated": False,
        "priority": 8,
        "speed": "very_fast",
        "accuracy": "medium"
    },
    "nikto": {
        "name": "nikto",
        "binary": "nikto",
        "ecosystem": "apt",
        "install_cmd": "apt install nikto",
        "version_flags": ["-Version"],
        "version_required": ">=2.1.6",
        "category": "web",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://cirt.net/Nikto2",
        "deprecated": False,
        "priority": 7,
        "speed": "medium",
        "accuracy": "medium"
    },
    "wifite": {
        "name": "wifite",
        "binary": "wifite",
        "ecosystem": "apt",
        "install_cmd": "apt install wifite",
        "version_flags": ["--help"],
        "version_required": ">=2.0",
        "category": "wireless",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/derv82/wifite2",
        "deprecated": False,
        "priority": 9,
        "speed": "medium",
        "accuracy": "high"
    },
    "responder": {
        "name": "responder",
        "binary": "responder",
        "ecosystem": "apt",
        "install_cmd": "apt install responder",
        "version_flags": ["--help"],
        "version_required": ">=3.0",
        "category": "exploitation",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/lgandx/Responder",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "crackmapexec": {
        "name": "crackmapexec",
        "binary": "crackmapexec",
        "ecosystem": "pip",
        "install_cmd": "pip install crackmapexec",
        "version_flags": ["--version"],
        "version_required": ">=5.0",
        "category": "exploitation",
        "risk": "high",
        "alternatives": ["netexec"],
        "docs_url": "https://github.com/byt3bl33d3r/CrackMapExec",
        "deprecated": False,
        "priority": 10,
        "speed": "fast",
        "accuracy": "high"
    },
    "enum4linux": {
        "name": "enum4linux",
        "binary": "enum4linux",
        "ecosystem": "apt",
        "install_cmd": "apt install enum4linux",
        "version_flags": ["-h"],
        "version_required": ">=0.8",
        "category": "recon",
        "risk": "low",
        "alternatives": ["enum4linux-ng"],
        "docs_url": "https://github.com/portcullislabs/enum4linux",
        "deprecated": False,
        "priority": 8,
        "speed": "medium",
        "accuracy": "medium"
    },
    "searchsploit": {
        "name": "searchsploit",
        "binary": "searchsploit",
        "ecosystem": "apt",
        "install_cmd": "apt install exploitdb",
        "version_flags": ["--version"],
        "version_required": ">=1.0",
        "category": "exploitation",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/offensive-security/exploitdb",
        "deprecated": False,
        "priority": 9,
        "speed": "fast",
        "accuracy": "high"
    },
    "ghidra": {
        "name": "ghidra",
        "binary": "ghidraRun",
        "ecosystem": "script",
        "install_cmd": "echo 'Download from https://ghidra-sre.org/'",
        "version_flags": ["--help"],
        "version_required": ">=10.0",
        "category": "reversing",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://ghidra-sre.org/",
        "deprecated": False,
        "priority": 10,
        "speed": "slow",
        "accuracy": "high"
    },
    "radare2": {
        "name": "radare2",
        "binary": "r2",
        "ecosystem": "apt",
        "install_cmd": "apt install radare2",
        "version_flags": ["-v"],
        "version_required": ">=5.0",
        "category": "reversing",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://www.radare.org/",
        "deprecated": False,
        "priority": 9,
        "speed": "fast",
        "accuracy": "high"
    },
    "binwalk": {
        "name": "binwalk",
        "binary": "binwalk",
        "ecosystem": "apt",
        "install_cmd": "apt install binwalk",
        "version_flags": ["--help"],
        "version_required": ">=2.0",
        "category": "reversing",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/ReFirmLabs/binwalk",
        "deprecated": False,
        "priority": 8,
        "speed": "medium",
        "accuracy": "high"
    },
    "tcpdump": {
        "name": "tcpdump",
        "binary": "tcpdump",
        "ecosystem": "apt",
        "install_cmd": "apt install tcpdump",
        "version_flags": ["--version"],
        "version_required": ">=4.9",
        "category": "network",
        "risk": "low",
        "alternatives": ["tshark"],
        "docs_url": "https://www.tcpdump.org/",
        "deprecated": False,
        "priority": 10,
        "speed": "fast",
        "accuracy": "high"
    },
    "tshark": {
        "name": "tshark",
        "binary": "tshark",
        "ecosystem": "apt",
        "install_cmd": "apt install tshark",
        "version_flags": ["--version"],
        "version_required": ">=3.0",
        "category": "network",
        "risk": "low",
        "alternatives": ["wireshark"],
        "docs_url": "https://www.wireshark.org/docs/man-pages/tshark.html",
        "deprecated": False,
        "priority": 9,
        "speed": "medium",
        "accuracy": "high"
    },
    "socat": {
        "name": "socat",
        "binary": "socat",
        "ecosystem": "apt",
        "install_cmd": "apt install socat",
        "version_flags": ["-V"],
        "version_required": ">=1.7",
        "category": "network",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "http://www.dest-unreach.org/socat/",
        "deprecated": False,
        "priority": 9,
        "speed": "fast",
        "accuracy": "high"
    },
    "bettercap": {
        "name": "bettercap",
        "binary": "bettercap",
        "ecosystem": "apt",
        "install_cmd": "apt install bettercap",
        "version_flags": ["-version"],
        "version_required": ">=2.30",
        "category": "network",
        "risk": "high",
        "alternatives": ["ettercap"],
        "docs_url": "https://www.bettercap.org/",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "mitmproxy": {
        "name": "mitmproxy",
        "binary": "mitmproxy",
        "ecosystem": "pip",
        "install_cmd": "pip install mitmproxy",
        "version_flags": ["--version"],
        "version_required": ">=8.0",
        "category": "web",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://mitmproxy.org/",
        "deprecated": False,
        "priority": 9,
        "speed": "medium",
        "accuracy": "high"
    },
    "wafw00f": {
        "name": "wafw00f",
        "binary": "wafw00f",
        "ecosystem": "pip",
        "install_cmd": "pip install wafw00f",
        "version_flags": ["--version"],
        "version_required": ">=2.1",
        "category": "web",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/EnableSecurity/wafw00f",
        "deprecated": False,
        "priority": 8,
        "speed": "fast",
        "accuracy": "medium"
    },
    "dnsrecon": {
        "name": "dnsrecon",
        "binary": "dnsrecon",
        "ecosystem": "apt",
        "install_cmd": "apt install dnsrecon",
        "version_flags": ["-h"],
        "version_required": ">=0.10",
        "category": "recon",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/darkoperator/dnsrecon",
        "deprecated": False,
        "priority": 8,
        "speed": "medium",
        "accuracy": "high"
    },
    "theharvester": {
        "name": "theharvester",
        "binary": "theHarvester",
        "ecosystem": "apt",
        "install_cmd": "apt install theharvester",
        "version_flags": ["-h"],
        "version_required": ">=4.0",
        "category": "recon",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/laramies/theHarvester",
        "deprecated": False,
        "priority": 7,
        "speed": "medium",
        "accuracy": "medium"
    },
    "spiderfoot": {
        "name": "spiderfoot",
        "binary": "spiderfoot",
        "ecosystem": "pip",
        "install_cmd": "pip install spiderfoot",
        "version_flags": ["--version"],
        "version_required": ">=3.0",
        "category": "recon",
        "risk": "low",
        "alternatives": [],
        "docs_url": "https://github.com/smicallef/spiderfoot",
        "deprecated": False,
        "priority": 6,
        "speed": "slow",
        "accuracy": "very_high"
    },
    "impacket": {
        "name": "impacket",
        "binary": "impacket-psexec",
        "ecosystem": "pip",
        "install_cmd": "pip install impacket",
        "version_flags": ["--help"],
        "version_required": ">=0.10",
        "category": "exploitation",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/fortra/impacket",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "evil-winrm": {
        "name": "evil-winrm",
        "binary": "evil-winrm",
        "ecosystem": "gem",
        "install_cmd": "gem install evil-winrm",
        "version_flags": ["--version"],
        "version_required": ">=3.0",
        "category": "exploitation",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/Hackplayers/evil-winrm",
        "deprecated": False,
        "priority": 9,
        "speed": "medium",
        "accuracy": "high"
    },
    "bloodhound-python": {
        "name": "bloodhound-python",
        "binary": "bloodhound-python",
        "ecosystem": "pip",
        "install_cmd": "pip install bloodhound",
        "version_flags": ["--help"],
        "version_required": ">=1.0",
        "category": "recon",
        "risk": "high",
        "alternatives": ["sharphound"],
        "docs_url": "https://github.com/fox-it/BloodHound.py",
        "deprecated": False,
        "priority": 10,
        "speed": "medium",
        "accuracy": "high"
    },
    "gau": {
        "name": "gau",
        "binary": "gau",
        "ecosystem": "go",
        "install_cmd": "go install github.com/lc/gau/v2/cmd/gau@latest",
        "version_flags": ["--version"],
        "version_required": ">=2.0",
        "category": "recon",
        "risk": "low",
        "alternatives": ["waybackurls"],
        "docs_url": "https://github.com/lc/gau",
        "deprecated": False,
        "priority": 8,
        "speed": "fast",
        "accuracy": "high"
    },
    "waybackurls": {
        "name": "waybackurls",
        "binary": "waybackurls",
        "ecosystem": "go",
        "install_cmd": "go install github.com/tomnomnom/waybackurls@latest",
        "version_flags": ["--help"],
        "version_required": ">=0.1",
        "category": "recon",
        "risk": "low",
        "alternatives": ["gau"],
        "docs_url": "https://github.com/tomnomnom/waybackurls",
        "deprecated": False,
        "priority": 7,
        "speed": "fast",
        "accuracy": "medium"
    },
    "commix": {
        "name": "commix",
        "binary": "commix",
        "ecosystem": "apt",
        "install_cmd": "apt install commix",
        "version_flags": ["--version"],
        "version_required": ">=3.0",
        "category": "exploitation",
        "risk": "high",
        "alternatives": [],
        "docs_url": "https://github.com/commixproject/commix",
        "deprecated": False,
        "priority": 9,
        "speed": "medium",
        "accuracy": "high"
    },
    "wpscan": {
        "name": "wpscan",
        "binary": "wpscan",
        "ecosystem": "gem",
        "install_cmd": "gem install wpscan",
        "version_flags": ["--version"],
        "version_required": ">=3.8",
        "category": "web",
        "risk": "medium",
        "alternatives": [],
        "docs_url": "https://wpscan.com/",
        "deprecated": False,
        "priority": 9,
        "speed": "medium",
        "accuracy": "high"
    },
    "wfuzz": {
        "name": "wfuzz",
        "binary": "wfuzz",
        "ecosystem": "pip",
        "install_cmd": "pip install wfuzz",
        "version_flags": ["--version"],
        "version_required": ">=3.0",
        "category": "web",
        "risk": "medium",
        "alternatives": ["ffuf"],
        "docs_url": "https://github.com/xmendez/wfuzz",
        "deprecated": False,
        "priority": 8,
        "speed": "fast",
        "accuracy": "medium"
    },
}

# Add more tools as needed - target 80-100 curated security tools
# This is a representative sample showing the structure

logger.info(f"Loaded {len(CORE_TOOLS)} core tools from metadata")
